apply plugin: "org.jetbrains.kotlin.jvm"
apply plugin: "jacoco"

repositories {
    google()
    mavenCentral()
}

sourceSets.main.java.srcDirs += file("../buildSrc/src/main/java")
sourceSets.main.resources.srcDirs += file("../buildSrc/src/main/resources")

dependencies {
    implementation gradleApi()
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "com.android.tools.build:gradle:9.2.1"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:2.3.21"
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}
check.dependsOn jacocoTestReport
