apply plugin: "org.jetbrains.kotlin.jvm"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}
apply plugin: "jacoco"

repositories {
    google()
    mavenCentral()
}

sourceSets.main.java.srcDirs += file("../buildSrc/src/main/java")
sourceSets.main.resources.srcDirs += file("../buildSrc/src/main/resources")

dependencies {
    implementation gradleApi()
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "com.android.tools.build:gradle:9.2.1"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:2.3.21"
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}
check.dependsOn jacocoTestReport
